import type { Food, MealRecommendation, PantryItem, UserProfile } from "../types/api";

export const food: Food = {
  id: "food-1",
  name: "Chicken Breast",
  brand: "Fresh",
  category: "protein",
  serving_size: 4,
  serving_unit: "oz",
  calories_per_serving: 200,
  protein_g_per_serving: 40,
  carbs_g_per_serving: 0,
  fat_g_per_serving: 5,
  sugar_g_per_serving: 0,
  fiber_g_per_serving: 0,
  sodium_mg_per_serving: 100,
  cost_per_serving: 2.5,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
};
export const pantryItem: PantryItem = {
  ...food,
  id: "pantry-1",
  food_id: food.id,
  food_name: food.name,
  servings_available: 4,
  max_servings_per_meal: 2,
  expiration_date: null,
  notes: "Freezer",
  is_available: true,
};
export const profile: UserProfile = {
  id: "user-1",
  email: "dev@example.com",
  username: "developer",
  name: "Dev User",
  age: 30,
  height_inches: 70,
  weight_pounds: 165,
  gender: null,
  calorie_goal: 2200,
  protein_goal: 150,
  carbs_goal: 230,
  fat_goal: 70,
  sodium_max: 2300,
  sugar_max: 50,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
};
export const recommendation: MealRecommendation = {
  is_feasible: true,
  feasibility_score: 94.2,
  items: [{ food_id: food.id, food_name: food.name, servings: 1.5 }],
  totals: {
    calories: 300,
    protein_g: 60,
    carbs_g: 0,
    fat_g: 7.5,
    sugar_g: 0,
    fiber_g: 0,
    sodium_mg: 150,
    cost: 3.75,
  },
  constraint_scores: { calories: 95 },
  constraints_met: { calories: true, protein: true },
  candidates_generated: 10000,
  valid_candidates_evaluated: 6800,
  disclaimer: "Best result from randomized search.",
};
